#!/bin/sh

# Useful options (man zshoptions)
zle_highlight=('paste:none')

# Disable beeping sound
unsetopt BEEP

# Source the other config files
source "$ZDOTDIR/zsh-functions"
zsh_add_file "zsh-aliases"
zsh_add_file "zsh-bindings"
zsh_add_file "zsh-prompt"

# Plugins
zsh_add_plugin "zsh-users/zsh-autosuggestions"
zsh_add_plugin "zsh-users/zsh-syntax-highlighting"

# Change keybind to accept zsh autosuggestion
bindkey '^o' autosuggest-accept
